config/routes.rb
Rails.application.routes.draw do
  resources :imports, only: [ :create, :new ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "imports#new"
end

app/models/affiliate.rb
class Affiliate < ApplicationRecord
  belongs_to :merchant

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :website_url, url: { allow_nil: true }
  validates :email, presence: true, email: { mode: :strict, require_fqdn: true }, uniqueness: { scope: :merchant_id }
  validates :commissions_total, numericality: { greater_than_or_equal_to: 0 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  has_many :affiliates

  validates :slug,
    presence: true,
    uniqueness: true,
    format: { with: /\A[a-z0-9]+(?:-[a-z0-9]+)*\Z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  def create
    # TODO: Implement CSV uploading

    raise NotImplementedError
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/imports/new.html.erb
<h1><%= image_tag "logo.svg" %></h1>

<%= form_with(url: imports_path, local: true, method: :post, html: { multipart: true }) do |form| %>
  <fieldset class="field">
    <%= form.label :file %>
    <%= form.file_field :file, accept: '.csv' %>
  </fieldset>

  <div class="actions">
    <%= form.submit "Upload and Import" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Importful" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>